spring.application.name=patient-api

server.port=8081

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
management.endpoints.web.exposure.include=health,info
spring.kafka.admin.auto-create=true

kafka.topic.patient-vitals=patient-vitals
spring.kafka.producer.properties.spring.json.add.type.headers=false